USE [master]
GO

/****** Object:  Database [TalentDatabase]    Script Date: 2018/2/9 ¤U¤È 06:54:12 ******/
CREATE DATABASE [TalentDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TalentDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TalentDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TalentDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TalentDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TalentDatabase] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TalentDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TalentDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TalentDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TalentDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TalentDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TalentDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [TalentDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TalentDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TalentDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TalentDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TalentDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TalentDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TalentDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TalentDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TalentDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TalentDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TalentDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TalentDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TalentDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TalentDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TalentDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TalentDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TalentDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TalentDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [TalentDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [TalentDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TalentDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TalentDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TalentDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TalentDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TalentDatabase] SET QUERY_STORE = OFF
GO

USE [TalentDatabase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TalentDatabase] SET  READ_WRITE 
GO


